# Generated by Django 2.1.5 on 2019-02-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
    ]
