# Generated by Django 2.1.5 on 2019-02-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190208_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(help_text='enter product name', max_length=200, verbose_name='Product Name'),
        ),
    ]
