# Generated by Django 2.0.6 on 2019-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190208_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=19),
        ),
    ]
