# Generated by Django 2.0.6 on 2019-02-09 09:13

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=products.models.upload_path),
        ),
    ]
